### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'math' during the execution of `ordpy.ordinal_distribution`

### ISSUE THREAD

**Issue by geans** [arthurpessa/ordpy#11]
### Problem Reference

https://github.com/arthurpessa/ordpy/blob/e4b71ec0a7ecb69a2b8247176955fc87f7d87de0/ordpy/ordpy.py#L510

### Problem

Newer versions of the numpy library do not contain the math object. This generates an error on line 510 of the ordpy.py file (referenced at the beginning of this text).

### Solution

A simple solution is to replace `np.math.factorial` with `math.factorial` (importing the math library).

```
...
import math
...
if len(probabilities)==math.factorial(dx*dy): 
...
```

> P.S.: Sou Gean de Maceió, Alagoas. Utilizei sua biblioteca no meu trabalho de mestrado (na UFAL) e continuo utilizando em pesquisa com alunos de graduação. Um artigo já foi lançado referenciando sua biblioteca. Agradeço pelo seu trabalho.

**Comment by arthurpessa** [comment]
Boa noite, Gean. 

Muito obrigado por ter apontado esse erro no nosso pacote. Nós ficamos muito felizes que o código tem sido útil a você!

Essa era a última linha de código que utilizava a função np.math.factorial uma vez que nós, anteriormente, já havíamos preferido a função math.factorial. Com essa mudança, o cálculo do fatorial fica mais consistente ao longo do código.

Qualquer outro problema, por favor, informe-nos.

Atenciosamente, 
Arthur.

**Comment by arthurpessa** [comment]
Boa noite, Gean.

Muito obrigado por ter apontado esse erro no nosso pacote. Seguimos a alteração sugerida por você e a publicamos a versão 1.1.5 do ordpy. Ficamos muito felizes que o código tem sido útil a você!

Essa era a última linha de código que utilizava a função np.math.factorial uma vez que nós, anteriormente, já havíamos preferido a função math.factorial. Com essa mudança, o cálculo do fatorial fica mais consistente ao longo do código.

Qualquer outro problema, por favor, informe-nos.

Atenciosamente,
Arthur.
