### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by sufex00** [arthurpessa/ordpy#8]
Hello,

I'd like to begin by expressing my appreciation for the recent developments in the package, which have undoubtedly enhanced its capabilities. However, while exploring these changes  (commit  [here](https://github.com/arthurpessa/ordpy/commit/3cf6f5559241c291cd463c21ce27244d4d62da49)), I've encountered an issue that I believe deserves attention.

The situation arises when the `ordered_variable` is set to `True`, leading to the return of the `dict_probs` dictionary. Upon closer inspection, I noticed that the keys obtained using `.keys()` are in string format. Regrettably, this causes an error, as depicted in **screenshots 1 and 2**.

It's worth noting that this error seems to be consistently triggered whenever a distribution with a **missing** symbol is **involved**. On a more positive note, I'd like to propose a potential solution: by adjusting the return line 523 to incorporate the code snippet 
```return np.asarray(list(all_symbols)), np.asarray(list(dict_probs.values()))```, 

we might be able to address the issue effectively. This optimistic outlook is supported by the example showcased in screenshot 3.

With a mindset of continuous improvement in mind, I'm submitting this issue in hopes of collaboratively resolving the matter. Thank you for your dedication to maintaining and enhancing this remarkable package. Your attention to this matter is highly valued.

![screenshot1](https://github.com/arthurpessa/ordpy/assets/7265974/9b72b803-8483-4eda-a760-acab1f6a8cd9)

![screenshot2](https://github.com/arthurpessa/ordpy/assets/7265974/e7bba484-9374-48fc-b318-9eb932819b1a)

![screenshot3](https://github.com/arthurpessa/ordpy/assets/7265974/cff6bd0f-5ff0-4366-87bc-deece3a7fd64)

**Comment by hvribeiro** [comment]
Hi @sufex00,

Thank you for your comments. I am not quite sure I understand the issue you mention. Is it an error, or only the format of the permutation symbols that would be preferable as an array? We have recently modified this part to use dictionary keys because we find it better for creating other data structures.

Best wishes, Haroldo.
